[package]
name = "auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
validr = "^0.3"
chrono = { version = "0.4.23", features = ["serde"] }
serde = "*"
serde_json = "*"

context = { path = "../context" }
error = { path = "../error" }
entity = { path = "../entity" }
util = { path = "../util" }

[dev-dependencies]
async-std = { version = "^1", features = ["attributes", "tokio1"] }

context = { path = "../context", features = ["mock"] }
entity = { path = "../entity", features = ["mock"] }
