version: "3"

services:
  nosp-pg:
    image: postgres:15.4
    container_name: nosp-pg
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgres
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: supersecret
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    user: root

  nosp-pga:
    image: dpage/pgadmin4:7
    container_name: nosp-pga
    ports:
      - 5050:80
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nospace.local
      PGADMIN_DEFAULT_PASSWORD: supersecret
    user: root
