[package]
name = "cryptfns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cryptfns"
path = "src/lib.rs"

[features]
mock = []

[dependencies]
rand = "^0.7"
ed25519-dalek = "^1.0"
bip39 = "^2"

error = { path = "../error" }
