[package]
name = "cryptfns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cryptfns"
path = "src/lib.rs"

[features]
mock = []

[dependencies]
rand = "^0.7"
bip39 = { version = "^2", features = ["rand_core", "rand"] }
secp256k1 = { version = "^0.26", features = ["bitcoin_hashes"] }
hex = "^0.4"

serde = "*"
serde_json = "*"

error = { path = "../error" }
