[package]
name = "cryptfns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cryptfns"
path = "src/lib.rs"

[features]
mock = []

[dependencies]
rand = "^0.8"
rsa = { version = "^0.8", features = ["sha2"] }
base64 = "^0.21"
hex = "^0.4"

serde = "*"
serde_json = "*"

error = { path = "../error" }
