[package]
name = "error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "error"
path = "src/lib.rs"

[dependencies]
thiserror = "^1"
sea-orm = { version = "^0.10", features = [
  "sqlx-postgres",
  "sqlx-sqlite",
  "runtime-actix-rustls",
] }
validr = "^0.3"
actix-web = "^4"
ed25519-dalek = "^1.0"
secp256k1 = "^0.26"
bip39 = "^2"
serde = "*"
serde_json = "*"
